# Numpyの基礎：配列とベクトル演算

* ベクトル化記法による高速計算。データの変更、整頓、取り出しやフィルタリング、変更などの操作
* 一般的な配列操作。ソートや重複除外操作、集合計算
* 効率的な記述統計学的データ操作。またそれに必要なデータの統合、要約
* 種類の異なるデータセットに対する結合や統合といった、データ整理や関係データ処理
* 配列内での条件記述。ループを書くことなく、配列内で直接if-elif-else相当の制御を記述
* グループ単位でのデータ操作(データ集計、データ構造の変更、関数の適用)

## 4.1 Numpy ndarray:多次元配列オブジェクト(P95)

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[ 0.70028973, -0.7244043 ,  1.32296933],
       [ 0.86410928, -0.44093423,  0.89605761]])

In [4]:
data *10

array([[ 7.00289735, -7.24404299, 13.22969325],
       [ 8.64109275, -4.40934226,  8.96057611]])

- nadarrayの特徴
- すべて同じ型である必要がある
- shapeとdtypeという属性がある
    - shapeは配列の次元ことの要素数を格納するタプル
    - dtypeは配列要素の型を表示

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

## 4.1.1 ndarrayの生成

- array関数を用いる(引数にシーケンス型やそれに類する形式の変数)

In [7]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1[0]

6.0

- 配列の内部構造はndimとshapeで表現される
    - ndimは配列の次元数を表示する

In [8]:
# 配列の次元数を確認する
arr1.ndim

1

- np.zeorsはすべての要素に0を設定

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

- np.onesはすべての要素に1を設定

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

- np.emptyは各要素を初期化せずに戻す　 ※前に作成した配列が初期化(0)にならない

In [12]:
np.empty((2,2))

array([[1.44442819e-311, 7.23614903e+159],
       [1.28014464e-152, 6.20198208e+223]])

In [13]:
np.empty((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- np.arangeは等間隔に増減させた要素を満たす

In [14]:
c=np.arange(15)

In [15]:
d = np.asarray(c)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
e = np.array(c)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

## ☆ndarray生成関数まとめ☆

- array：入力にリスト、タプルなどで生成する。dtypeは推測されたもの、明示的に指定されたものを使用
- asarray：array同様、ただし入力がndarrayだとコピーを作成できない　
    - array()がオブジェクト自体をコピー（別人格）
    - asarray()が参照オブジェクト（名前が違うが中身同じ）
- arange: range関数と同じ動作
- ones,ones_like：onesは要素全て1で埋める、ones_likeは引数に別のndarrayを受け、  
  それをテンプレートして全部1を埋める
- empty,empty_like: ones,ones_like同様だが、各要素は初期化されず不定のまま
- full,full_like: 要素を全て指定した値で埋める
     - np.full(shape, fill_value, dtype=None, order='C')
- eye,identity: N×Nの単位行列を作成       　　       　　　　　　　　　　　　　 
    - np.eye(2, dtype=int)

## 4.1.2 ndarrayのデータ型

In [18]:
arr1 = np.array([1,2,3], dtype=np.int32) 

In [19]:
arr1.dtype

dtype('int32')

- 型変換する場合はastypeメソッド、コピーした新しいndarrayを戻す ※必ず新規ndarrayが生成される

In [20]:
float_arr = arr1.astype(np.float64)

In [21]:
float_arr.dtype

dtype('float64')

In [22]:
empty_uint32 = np.empty(8,dtype='u4')

In [23]:
empty_uint32

array([2977439600,        680, 1293951008, 1629517921, 1819243362,
        543519861, 1717987684, 1852142181], dtype=uint32)

## 4.1.3 ndarrayの算術演算

In [24]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [25]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [27]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [28]:
arr + arr2

array([[ 1.,  6.,  4.],
       [11.,  7., 18.]])

In [29]:
arr * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

## 4.1.4 インデックス参照とスライシング基礎

1. スライスのあらゆる変更はオリジナルのndarryに反映される
2. ブールインデックス参照で抽出されたデータは必ず元データのコピーが生成
3. ファンシーインデックス参照は常に元データのコピーが生成
4. 転置はオリジナル行列を再構成、コピーの生成無

In [30]:
arr = np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[3:6]

array([3, 4, 5])

In [33]:
arr[5:8]=12

In [34]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- スライスをビューではなくコピーして生成が必要な場合はarr[5:8].copy()

- 2次元以上の高次元配列の場合

In [36]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2d[2]

array([7, 8, 9])

In [38]:
arr2d[0][2]

3

In [39]:
arr2d[1,2]

6

## 4.1.4.1 スライスによるインデックス参照

In [40]:
arr2d[:2] #arr2の最初の2行を切り出す

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [42]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

## 4.1.5 ブールインデックス参照

- 比較演算子を使用してブールインデックス参照が出来る

In [43]:
names = np.array(["AA","BB","CC","AA","CC","BB",'BB'])

In [44]:
data = np.random.randn(7,4)

In [45]:
data

array([[-2.26603715e-01, -9.43157968e-01,  7.41271755e-01,
        -3.61798578e-01],
       [-4.69799722e-01, -5.62542736e-01, -1.82325545e+00,
         1.30452515e+00],
       [-9.06911766e-01,  8.41448221e-02, -2.03307839e-01,
         8.02478630e-01],
       [-1.04106506e+00,  5.84558465e-01, -1.01170987e+00,
         4.96979459e-01],
       [ 1.20356441e+00,  2.47904160e-01,  6.12048395e-01,
        -6.75981564e-06],
       [ 8.83277268e-01, -3.50067935e-01, -4.57944821e-01,
         5.24808676e-01],
       [ 1.19953920e+00,  7.47791878e-01,  1.88653065e-01,
         1.78724631e-01]])

In [46]:
names == 'AA'

array([ True, False, False,  True, False, False, False])

In [47]:
data[names == 'AA',2:] #必ず参照先配列の軸と真偽値配列の要素数が一致していること

array([[ 0.74127176, -0.36179858],
       [-1.01170987,  0.49697946]])

- 'AA'以外の名前だと、!= や　~を使う   ←真偽を逆転させる

In [48]:
names != 'AA'

array([False,  True,  True, False,  True,  True,  True])

In [49]:
data[~(names == 'AA')]

array([[-4.69799722e-01, -5.62542736e-01, -1.82325545e+00,
         1.30452515e+00],
       [-9.06911766e-01,  8.41448221e-02, -2.03307839e-01,
         8.02478630e-01],
       [ 1.20356441e+00,  2.47904160e-01,  6.12048395e-01,
        -6.75981564e-06],
       [ 8.83277268e-01, -3.50067935e-01, -4.57944821e-01,
         5.24808676e-01],
       [ 1.19953920e+00,  7.47791878e-01,  1.88653065e-01,
         1.78724631e-01]])

- 2つ以上の条件組み合わせだと,&(and)や|（or）を使う

In [50]:
mask = (names == 'AA') | (names == 'BB')

In [51]:
data[mask]

array([[-0.22660372, -0.94315797,  0.74127176, -0.36179858],
       [-0.46979972, -0.56254274, -1.82325545,  1.30452515],
       [-1.04106506,  0.58455846, -1.01170987,  0.49697946],
       [ 0.88327727, -0.35006793, -0.45794482,  0.52480868],
       [ 1.1995392 ,  0.74779188,  0.18865306,  0.17872463]])

- 真偽値配列を使って各要素に値代入できる

In [52]:
data[data < 0] =0

In [53]:
data

array([[0.        , 0.        , 0.74127176, 0.        ],
       [0.        , 0.        , 0.        , 1.30452515],
       [0.        , 0.08414482, 0.        , 0.80247863],
       [0.        , 0.58455846, 0.        , 0.49697946],
       [1.20356441, 0.24790416, 0.6120484 , 0.        ],
       [0.88327727, 0.        , 0.        , 0.52480868],
       [1.1995392 , 0.74779188, 0.18865306, 0.17872463]])

## 4.1.6 ファンシーインデックス参照

- インデックス参照に整数配列を用いる

In [54]:
arr = np.empty([8,4])

In [55]:
for i in range(8):
    arr[i] = i

In [56]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [57]:
# ある特定の順序で行を抽出するにはその順番を示す整数リストを渡す
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [58]:
arr = np.arange(32).reshape((8,4))

In [59]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
arr[[1,5,7,2],[0,3,1,2]] #列のそれぞれの位置の値を取り出している

array([ 4, 23, 29, 10])

In [61]:
arr[[1,5,7,2]][:,[0,3,1,2]] #行指定と列の順番を変えている

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

- ファンシーインデックス参照は常に元データのコピー

## 4.1.7 転置行列、行と列の入れ替え

- 転置はオリジナル行列を再構成、コピーの生成無
- 置はtranspose関数かTかswapaxes

In [62]:
arr = np.arange(15).reshape((3,5))

In [63]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [65]:
arr = np.random.randn(6,3)

In [66]:
arr

array([[ 0.30945766,  0.66358164, -0.01199792],
       [-2.88074874, -0.70701969,  0.50524096],
       [ 1.06563009, -0.66028196, -0.29220571],
       [ 0.77405199,  0.18360191, -0.03633929],
       [ 0.56412833,  1.85599478,  0.84657837],
       [ 0.20951252,  0.3321235 ,  0.12462794]])

In [67]:
np.dot(arr.T,arr) #np.dotは内積計算

array([[10.49133755,  2.79720087, -1.29500685],
       [ 2.79720087,  4.96492201,  1.43372618],
       [-1.29500685,  1.43372618,  1.07434415]])

In [68]:
arr = np.arange(16).reshape((2,2,4))

In [69]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

- 高次元配列の場合transposeの引数に軸の順序を与え、その順に入れ替え出来る

In [70]:
arr.transpose((0,2,1)) #元の0軸はここに移動, 元の2軸はここに移動, 元の1軸はここに移動

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

- wapaxesは任意の軸順序で転置出来る

In [71]:
arr.swapaxes(0,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

## 4.2　ユニバーサル関数：すべての配列要素への関数適用

- ・引数に１つのnaddaryを取るものを単項ufunc

In [72]:
np.sqrt(arr)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131]],

       [[2.82842712, 3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739, 3.87298335]]])

In [73]:
np.exp(arr)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]],

       [[2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]]])

- 引数に2つのnaddaryを取るものを二項ufunc

In [74]:
x = np.random.randn(8)
y = np.random.randn(8)

In [75]:
np.maximum(x,y)

array([ 1.39228857,  1.17493225,  1.88868502,  1.52211379,  0.09852439,
       -0.47288748,  1.52022586,  1.55313344])

- 整数と小数からなる配列を分割

In [76]:
arr = np.random.randn(7) * 5
arr

array([10.75005814, -6.11828667, -0.15672279,  9.70156141,  4.54440594,
       -5.03857222, -1.6148722 ])

In [77]:
aa, bb = np.modf(arr)

In [78]:
aa #小数部分

array([ 0.75005814, -0.11828667, -0.15672279,  0.70156141,  0.54440594,
       -0.03857222, -0.6148722 ])

In [79]:
bb # 整数部分

array([10., -6., -0.,  9.,  4., -5., -1.])

### ■単項ufunc　　
- abs,fabs: 絶対値を計算する、fabsは高速版で対象を整数と小数に限定
- sqrt：平方根を計算する　arr**0.5と同等
- square：2乗を計算する　arr**2と同等
- exp：自然対数の底eのべき乗(e2)を計算 
- log,log10,log2：対数計算
- sign：各要素の符号を返す、正は1、ゼロは0、負は-1
- ceil：各要素の切り上げ計算
- floor：各要素の切り捨て計算
- rint：各要素の丸め値を計算　その数にもっとも近い整数をとる
- modf：各要素ごとに整数部分と小数部分に分割し、それぞれの配列を返す
- isnan：要素ごとにNaNかどうか判定し真偽値配列を返す
- isfinite,isinf：isfiniteは有限(infでなく、NaNでもない)を判定し真偽値配列を返す
    - isinfは無限(inf)かどうか判定し真偽値配列を返す
- cos,cosh,sin,sinh,tan,tanh: 余弦、正弦、正接を計算
- arccos,arccosh,arcsin,arcsinh,arctan,arctanh: 逆余弦、逆正弦、逆正接を計算　
- logical_not: 各要素の論理否定を返す。~arrと同じ

## ■二項ufunc
- add：配列の要素ごとの和をとる
- subtract：1番目の配列から2番目の配列のそれぞれの差をとる
- multiply: 要素ごとに積をとる
- divide,floor_divide: divideは要素ごとの商をとる、floor_divideは商をとってあまりを切り捨てる
- power: 1番目の配列要素を底とし、2番目の配列要素でべき乗する
- maximum,fmax: 各要素の最大値を計算、要素がNaNの場合、minimumはNaNを選びfmaxはNaNでない要素を選ぶ
- minimum,fmin：上記のmin版
- mod: 要素ごとの剰余を計算
- copysign：1番目の配列の値に2番目の配列要素の符号をつける
- greater, greater_equal, less, less_equal, equal, not_equal:比較結果を真偽値で返す
    - >, >=, <, <=, ==, != と同じ
- logical_and,logical_or,logical_xor:論理演算する　中置二項演算と同等 &, |, ^

## 4.3　nadarrayによる配列指向プログラミング

### 4.3.1 条件制御のndarrayでの表現

In [82]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [111]:
#三項演算子をリスト内表記で書いた場合
result =[ (x if c else y)
         for x,y,c in zip(xarr,yarr,cond)]

In [84]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

- np.whereはPythonの三項演算子(条件文)のベクトル演算版
    - np.whereの主な使用場面は、ある配列を元に別の配列を作るとき

In [113]:
result_w = np.where(cond,xarr,yarr)
result_w

array([1.1, 2.2, 1.3, 1.4, 2.5])

## 4.3.2 数学関数、統計関数

- Numpyの統計関数はndarray配列全体、又は特定の軸を中心とした統計処理ができる
- sumやmeanは配列の次元を下げる処理で次元削減と呼ばれる

In [127]:
arr= np.random.randn(5,4)

In [128]:
arr

array([[-0.52211233,  0.22208424, -0.03421426, -0.56522422],
       [ 0.34304638,  0.31317923,  2.85348466, -0.09646781],
       [-0.0933846 ,  0.51948134,  0.45519527, -1.40440056],
       [-0.38429608, -0.43277142,  0.77202648, -1.23275979],
       [-1.116749  ,  0.14116285, -0.21563777,  0.53775005]])

In [130]:
arr.mean() #np.mean(arr)でもいい

0.0029696323330785646

In [131]:
arr.sum()

0.05939264666157129

In [132]:
arr.sum(axis=0) #行ことに合計を計算 arr.sum(0)でもいい

array([-1.77349564,  0.76313623,  3.83085438, -2.76110233])

In [134]:
arr.sum(axis=1) #列ごとに合計を計算

array([-0.89946657,  3.41324246, -0.52310856, -1.27780081, -0.65347387])

In [135]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [137]:
arr.cumsum() #途中経過を含めた累積の計算結果を返す

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

### ■基本的なndarrayの統計関数
- sum: 配列の和を指定された軸に沿って計算、長さ0の配列は0を返す
- mean: 算術平均、長さ0の配列はNaNを返す
- std,var：標準偏差、分散
- min,max：最小値、最大値           
- argmin,argmax：最小値/最大値を持つインデックス
- cumsum: 累積和
- cumprod：累積積

## 4.3.3 真偽値配列関数

- 真偽値に関数を適用するとき、Trueは1、Falseは0として扱われる

In [139]:
(arr>0).sum() #正の個数を数える

7

- anyは要素に1個でもTrueがあるか確認できる
- allは要素全てがTrueか確認できる
- any,allは真偽値配列以外でも使用可、この場合、0以外がTrueとみなされる

In [92]:
bools = np.array([False,False,True])
bools.any()

True

In [93]:
arr.any()

True

In [94]:
arr.all()

False

## 4.3.4 ソート

- sort関数で並び替え可能、これは元のndarrayを直接置換している
- sortにはnp.ndarray.sort関数とnp.sort関数がある

In [140]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [142]:
arr.sort()
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [144]:
arr5 = np.random.randn(5,3)
arr5

array([[-2.41026044,  0.95099983, -1.69094313],
       [-1.03221525, -1.0875674 ,  0.95501857],
       [-0.10060826,  1.52743906,  1.75039584],
       [ 0.16781955, -0.21561226,  1.17181574],
       [ 0.34664556,  2.28319702, -1.39700039]])

In [147]:
arr5.sort(0) #列ごとにsort
arr5

array([[-2.41026044, -1.0875674 , -1.69094313],
       [-1.03221525, -0.21561226, -1.39700039],
       [-0.10060826,  0.95099983,  0.95501857],
       [ 0.16781955,  1.52743906,  1.17181574],
       [ 0.34664556,  2.28319702,  1.75039584]])

In [149]:
arr5.sort(1) #行ごとにsort
arr5

array([[-2.41026044, -1.69094313, -1.0875674 ],
       [-1.39700039, -1.03221525, -0.21561226],
       [-0.10060826,  0.95099983,  0.95501857],
       [ 0.16781955,  1.17181574,  1.52743906],
       [ 0.34664556,  1.75039584,  2.28319702]])

- np.sort関数

In [150]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [151]:
y1 = np.sort(arr) #配列xの要素を昇順ソートします
y2 = np.sort(arr)[::-1] #配列xの要素を降順ソートします

In [152]:
y1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [153]:
y2

array([7, 6, 5, 4, 3, 2, 1, 0])

## 4.3.5 集合関数：uniqueなど

- np.uniqueは配列要素から重複を取り除き、ソートした結果を返す

In [154]:
names = np.array(["AA","BB","CC","AA","CC","BB",'BB'])

In [104]:
np.unique(names)

array(['AA', 'BB', 'CC'], dtype='<U2')

In [155]:
# Python標準機能で書くと
sorted(set(names))

['AA', 'BB', 'CC']

### NumPyの集合関数
- unique(x): 配列xに対し重複削除してソート
- intersectid(x,y)：配列x,yのうち、共通する要素を取り出しソートする(積集合)
- union1d(x,y): 配列x,yのうち、少なくとも一方に存在する要素を取り出しソートする(和集合)
- in1d(x,y): 配列xの各要素に対し配列yが含まれているか真偽値配列として返す
- setdiff1d(x,y): 配列xから配列yに存在する要素を取り除きソートする(差集合)
- setxor1d(x,y): 配列x,yのうちどちらか一方にのみ存在する要素を取り出す(両方に含まれる要素は除く)

## 4.5　行列計算(P126)

- NumPyで内積を計算するためには関数dotを使う

In [105]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])

In [106]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [107]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [108]:
np.ones(3)

array([1., 1., 1.])

In [157]:
np.dot(x, np.ones(3))

array([ 6., 15.])

- Python3.5から行列の掛け算を表す二項演算子として@記号がある

In [158]:
x @ np.ones(3)

array([ 6., 15.])

- 標準的な行列の分解、逆、行列式の計算機能はnumpy.linalgモジュールで提供されている  
  from numpy.linalg import inv, qr

### よく用いられるnumpy.linalg関数
- diag：正方行列の対角要素を1次元配列として返す
- dot：２つの行列の内積を計算
- trace：対角要素の総和を計算する
- det：行列式を計算
- eig：正方行列に対して固有値および固有値ベクトルを計算する
- inv：正方行列に対して逆行列を計算 
- pinv：ムーアーペンローズの疑似逆行列を計算
- qr：qr分解を計算
- svd：特異値分解を計算する
- solve：正方行列Aに対して線形方程式Ax=bをxに対して解く
- lstsq:Ax=bに対して最小二乗法による近似を求める

## 4.5 疑似乱数生成(P128)

- Python組み込みのrandomを補完する形でnp.randomモジュールがある  
さまざまな種類の確率分布関数に基づく乱数値を生成できる

In [109]:
sample = np.random.normal(size=(4,4))

In [110]:
sample

array([[-0.38572133,  0.28932184,  0.55964576, -2.08084359],
       [ 1.37151385, -0.90881044,  0.2693955 , -0.23158442],
       [ 0.1582887 , -0.69253912, -0.56833533, -1.21009991],
       [ 0.16141823, -0.44117508, -0.17989595,  1.04927563]])

- numpy.randomで提供される乱数データはいずれも共通(グローバル)乱数シードを参照する  
  グローバル参照を避けるにはnumpy.random.RandomStateを用いると他と分離される

## 代表的なnumpy.random関数
- seed： 乱数生成器のシード
- permutation: 引数が配列だとランダムに並べた新しい配列を返す  
  引数が整数だとその引数でnp.arangeを呼び出し結果をランダムに並べた配列を返す
- shuffle： その配列自体の要素をランダムに並べ替える
- rand: 連続一様分布に従う乱数を返す
- randint: 与えられた整数範囲内での整数乱数を返す
- randn： 平均0、標準偏差1である正規分布に従う乱数を返す
- binomial： 二項分布に従う乱数を返す
- normal： 正規分布に従う乱数を返す
- beta： ベータ分布に従う乱数を返す
- chisquare： カイ二乗に従う乱数を返す
- gamma： ガンマ分布に従う乱数を返す
- uniform： 区間[0,1)の一様分布に従う乱数を返す